import {stockDirectory} from './stocks.js';
const rows=[
['^NSEI','NIFTY 50','India','Index'],['^NSEBANK','NIFTY BANK','India','Index'],['^BSESN','SENSEX','India','Index'],['^INDIAVIX','INDIA VIX','India','Index'],['^NSMIDCP','NIFTY NEXT 50','India','Index'],['^CNXIT','NIFTY IT','India','Index'],['^CNXAUTO','NIFTY AUTO','India','Index'],['^CNXPHARMA','NIFTY PHARMA','India','Index'],['^CNXFMCG','NIFTY FMCG','India','Index'],['^CNXMETAL','NIFTY METAL','India','Index'],['^CNXENERGY','NIFTY ENERGY','India','Index'],['^CNXPSUBANK','NIFTY PSU BANK','India','Index'],['NIFTY_FIN_SERVICE.NS','NIFTY FIN SERVICE','India','Index'],['NIFTY_PVT_BANK.NS','NIFTY PVT BANK','India','Index'],['^CNXREALTY','NIFTY REALTY','India','Index'],['^CNXMEDIA','NIFTY MEDIA','India','Index'],['^CNXINFRA','NIFTY INFRA','India','Index'],['^CNXPSE','NIFTY PSE','India','Index'],['^CNXCONSUM','NIFTY CONSUMPTION','India','Index'],['^CNXCMDT','NIFTY COMMODITIES','India','Index'],['^NSEMDCP50','NIFTY MIDCAP 50','India','Index'],['^CNXSC','NIFTY SMALLCAP 100','India','Index'],
['^GSPC','S&P 500','Global','Index'],['^IXIC','NASDAQ','Global','Index'],['^DJI','DOW JONES','Global','Index'],['^FTSE','FTSE 100','Global','Index'],['^N225','NIKKEI 225','Global','Index'],['^KS11','KOSPI','Global','Index'],
['AAPL','Apple','US','Technology'],['MSFT','Microsoft','US','Technology'],['NVDA','NVIDIA','US','Technology'],['AMZN','Amazon','US','Consumer'],['GOOGL','Alphabet','US','Technology'],['META','Meta Platforms','US','Technology'],['TSLA','Tesla','US','Auto'],['JPM','JPMorgan Chase','US','Financials'],['GS','Goldman Sachs','US','Financials'],['BRK-B','Berkshire Hathaway','US','Financials'],['AMD','Advanced Micro Devices','US','Technology'],['NFLX','Netflix','US','Media'],
['GC=F','Gold futures','Commodities','Commodity'],['SI=F','Silver futures','Commodities','Commodity'],['CL=F','WTI crude','Commodities','Commodity'],['BZ=F','Brent crude','Commodities','Commodity'],['NG=F','Natural gas','Commodities','Commodity'],['HG=F','Copper','Commodities','Commodity'],
['INR=X','USD / INR','FX','Currency'],['EURUSD=X','EUR / USD','FX','Currency'],['GBPUSD=X','GBP / USD','FX','Currency'],['JPY=X','USD / JPY','FX','Currency'],['BTC-USD','Bitcoin','Crypto','Crypto'],['ETH-USD','Ethereum','Crypto','Crypto'],['SOL-USD','Solana','Crypto','Crypto'],['^TNX','US 10Y yield','Rates','Yield'],['^IRX','US 13W yield','Rates','Yield'],['^TYX','US 30Y yield','Rates','Yield']
];
export const instruments=[...rows.map(([symbol,name,market,sector])=>({symbol,name,market,sector})),...stockDirectory.map(x=>({...x,symbol:x.symbol+'.NS',market:'India'}))];
export const directory=new Map(instruments.map(x=>[x.symbol,x]));
export const india=['RELIANCE','TCS','HDFCBANK','ICICIBANK','INFY','SBIN','BHARTIARTL','ITC','LT','AXISBANK','MARUTI','SUNPHARMA','TITAN','NTPC','TATASTEEL','BAJFINANCE'].map(x=>x+'.NS');
export const groups={'India':india,'US':rows.filter(x=>x[2]==='US').map(x=>x[0]),'Indices':rows.filter(x=>x[3]==='Index').map(x=>x[0]),'Commodities':rows.filter(x=>x[2]==='Commodities').map(x=>x[0]),'FX & Crypto':rows.filter(x=>['FX','Crypto'].includes(x[2])).map(x=>x[0]),'Rates':rows.filter(x=>x[2]==='Rates').map(x=>x[0])};
export const benchmarks=['^NSEI','^NSEBANK','^INDIAVIX','^GSPC','INR=X','BZ=F'];
export const short=s=>s?.replace('.NS','').replaceAll('_',' ') || '';
export const exchangeName=x=>({NSI:'NSE',BSE:'BSE',NMS:'NASDAQ',NGM:'NASDAQ',NCM:'NASDAQ',NYQ:'NYSE',PCX:'NYSE Arca',CCC:'Crypto',CCY:'FX',CMX:'COMEX',NYM:'NYMEX',SNP:'S&P',DJI:'Dow Jones'})[x]||x;
export const fmt=(n,d=2)=>Number.isFinite(n)?n.toLocaleString('en-IN',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
export const pct=n=>Number.isFinite(n)?`${n>=0?'+':''}${n.toFixed(2)}%`:'—';
export const compact=n=>Number.isFinite(n)?Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(n):'—';
export const search=q=>{q=(q||'').trim().toUpperCase();if(!q)return instruments.slice(0,12);const exact=x=>x.symbol===q||short(x.symbol)===q;return instruments.filter(x=>x.symbol.includes(q)||x.name.toUpperCase().includes(q)).sort((a,b)=>(exact(b)?1:0)-(exact(a)?1:0)).slice(0,16);};
